# Generated by Django 4.1 on 2022-09-04 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countermodel',
            old_name='count',
            new_name='press_count',
        ),
    ]
